/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as AdminSpacesSpaceIdIndexRouteImport } from './routes/_admin/spaces.$spaceId.index'
import { Route as AdminSpacesSpaceIdResolversNewRouteImport } from './routes/_admin/spaces.$spaceId.resolvers.new'
import { Route as AdminSpacesSpaceIdResolversResolverIdRouteImport } from './routes/_admin/spaces.$spaceId.resolvers.$resolverId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpacesSpaceIdIndexRoute = AdminSpacesSpaceIdIndexRouteImport.update({
  id: '/spaces/$spaceId/',
  path: '/spaces/$spaceId/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpacesSpaceIdResolversNewRoute =
  AdminSpacesSpaceIdResolversNewRouteImport.update({
    id: '/spaces/$spaceId/resolvers/new',
    path: '/spaces/$spaceId/resolvers/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSpacesSpaceIdResolversResolverIdRoute =
  AdminSpacesSpaceIdResolversResolverIdRouteImport.update({
    id: '/spaces/$spaceId/resolvers/$resolverId',
    path: '/spaces/$spaceId/resolvers/$resolverId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/spaces/$spaceId/': typeof AdminSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/resolvers/$resolverId': typeof AdminSpacesSpaceIdResolversResolverIdRoute
  '/spaces/$spaceId/resolvers/new': typeof AdminSpacesSpaceIdResolversNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/spaces/$spaceId': typeof AdminSpacesSpaceIdIndexRoute
  '/spaces/$spaceId/resolvers/$resolverId': typeof AdminSpacesSpaceIdResolversResolverIdRoute
  '/spaces/$spaceId/resolvers/new': typeof AdminSpacesSpaceIdResolversNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/': typeof AdminIndexRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/_admin/spaces/$spaceId/': typeof AdminSpacesSpaceIdIndexRoute
  '/_admin/spaces/$spaceId/resolvers/$resolverId': typeof AdminSpacesSpaceIdResolversResolverIdRoute
  '/_admin/spaces/$spaceId/resolvers/new': typeof AdminSpacesSpaceIdResolversNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/spaces/$spaceId/'
    | '/spaces/$spaceId/resolvers/$resolverId'
    | '/spaces/$spaceId/resolvers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/spaces/$spaceId'
    | '/spaces/$spaceId/resolvers/$resolverId'
    | '/spaces/$spaceId/resolvers/new'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/_admin/spaces/$spaceId/'
    | '/_admin/spaces/$spaceId/resolvers/$resolverId'
    | '/_admin/spaces/$spaceId/resolvers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/spaces/$spaceId/': {
      id: '/_admin/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof AdminSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/spaces/$spaceId/resolvers/new': {
      id: '/_admin/spaces/$spaceId/resolvers/new'
      path: '/spaces/$spaceId/resolvers/new'
      fullPath: '/spaces/$spaceId/resolvers/new'
      preLoaderRoute: typeof AdminSpacesSpaceIdResolversNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/spaces/$spaceId/resolvers/$resolverId': {
      id: '/_admin/spaces/$spaceId/resolvers/$resolverId'
      path: '/spaces/$spaceId/resolvers/$resolverId'
      fullPath: '/spaces/$spaceId/resolvers/$resolverId'
      preLoaderRoute: typeof AdminSpacesSpaceIdResolversResolverIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSpacesSpaceIdIndexRoute: typeof AdminSpacesSpaceIdIndexRoute
  AdminSpacesSpaceIdResolversResolverIdRoute: typeof AdminSpacesSpaceIdResolversResolverIdRoute
  AdminSpacesSpaceIdResolversNewRoute: typeof AdminSpacesSpaceIdResolversNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminSpacesSpaceIdIndexRoute: AdminSpacesSpaceIdIndexRoute,
  AdminSpacesSpaceIdResolversResolverIdRoute:
    AdminSpacesSpaceIdResolversResolverIdRoute,
  AdminSpacesSpaceIdResolversNewRoute: AdminSpacesSpaceIdResolversNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
