#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
ENV_FILE=".railway/deployment.env"
PROVIDER_SECRET_COUNT=0
CONTROL_VARS_FILE=""

require_command() {
  command -v "$1" >/dev/null 2>&1 || { warn "$1 is required"; exit 1; }
}

generate_credential() {
  openssl rand -hex 32
}

deployment_config() {
  node --experimental-strip-types scripts/deployment-config.ts "$@"
}

set_railway_value() {
  local service_name="$1" variable_name="$2" value="$3"
  printf '%s' "$value" | pnpm exec railway variable set "$variable_name" \
    --stdin --service "$service_name" \
    --project "$SHUTTER_RAILWAY_PROJECT_ID" \
    --environment "$SHUTTER_RAILWAY_ENVIRONMENT_ID" \
    --skip-deploys >/dev/null
  PROVIDER_SECRET_COUNT=$((PROVIDER_SECRET_COUNT + 1))
  printf '  %s✓ set%s Railway variable %s on %s\n' \
    "$GREEN" "$RESET" "$variable_name" "$service_name"
}

set_worker_secret() {
  local variable_name="$1" value="$2"
  printf '%s' "$value" | pnpm --filter @shutter/edge exec wrangler secret put \
    "$variable_name" --config wrangler.deploy.jsonc >/dev/null
  PROVIDER_SECRET_COUNT=$((PROVIDER_SECRET_COUNT + 1))
  printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$variable_name"
}

r2_bucket_exists() {
  pnpm --filter @shutter/edge exec wrangler r2 bucket info \
    "$SHUTTER_R2_BUCKET" --config wrangler.deploy.jsonc --json >/dev/null 2>&1
}

# load_control_vars — snapshot Shutter-Control's live variables to a private
# temp file so the credential stage can reuse existing values instead of
# regenerating them. Re-running the stage is a no-op by construction.
load_control_vars() {
  CONTROL_VARS_FILE=$(mktemp)
  chmod 600 "$CONTROL_VARS_FILE"
  pnpm exec railway variable list --service Shutter-Control \
    --project "$SHUTTER_RAILWAY_PROJECT_ID" \
    --environment "$SHUTTER_RAILWAY_ENVIRONMENT_ID" \
    --kv > "$CONTROL_VARS_FILE" 2>/dev/null || true
}

# existing_control_value NAME — the live value of NAME on Shutter-Control.
existing_control_value() {
  [[ -n "$CONTROL_VARS_FILE" ]] || return 1
  local line
  line=$(grep -E "^${1}=" "$CONTROL_VARS_FILE" | head -n1) || return 1
  printf '%s' "${line#*=}"
}

# reuse_or_generate KEY — keep the live Control value of KEY if one exists,
# otherwise generate a fresh credential. Never regenerates an existing value:
# SHUTTER_ENCRYPTION_KEY in particular seals every Capability Key and has no
# rotation tooling, so replacing it would be unrecoverable.
reuse_or_generate() {
  local key="$1" current
  if current=$(existing_control_value "$key") && [[ -n "$current" ]]; then
    printf -v "$key" '%s' "$current"
    note "reusing the existing $key"
  else
    printf -v "$key" '%s' "$(generate_credential)"
  fi
}

# reuse_or_ask_secret KEY "Prompt" — keep the live Control value if one
# exists, otherwise prompt the operator for it.
reuse_or_ask_secret() {
  local key="$1" prompt="$2" current
  if current=$(existing_control_value "$key") && [[ -n "$current" ]]; then
    printf -v "$key" '%s' "$current"
    note "reusing the existing $key"
  else
    ask_secret "$key" "$prompt"
  fi
}

write_public_inputs() {
  write_env SHUTTER_PROJECT_NAME "$SHUTTER_PROJECT_NAME"
  write_env SHUTTER_GITHUB_REPOSITORY "$SHUTTER_GITHUB_REPOSITORY"
  write_env SHUTTER_RAILWAY_REGION "$SHUTTER_RAILWAY_REGION"
  write_env SHUTTER_CONTROL_DOMAIN "$SHUTTER_CONTROL_DOMAIN"
  write_env SHUTTER_EDGE_WORKER_NAME "$SHUTTER_EDGE_WORKER_NAME"
  write_env SHUTTER_EDGE_DOMAIN "$SHUTTER_EDGE_DOMAIN"
  write_env SHUTTER_R2_BUCKET "$SHUTTER_R2_BUCKET"
  write_env SHUTTER_R2_ENDPOINT "$SHUTTER_R2_ENDPOINT"
  write_env SHUTTER_R2_REGION "$SHUTTER_R2_REGION"
  write_env SHUTTER_CLOUDFLARE_ZONE_ID "$SHUTTER_CLOUDFLARE_ZONE_ID"
  write_env SHUTTER_IMGPROXY_ALLOWED_SOURCES "$SHUTTER_IMGPROXY_ALLOWED_SOURCES"
}

require_command pnpm
require_command openssl
mkdir -p .railway

banner "Shutter deployment bootstrap"

stage "Deployment identity"
say "These public values describe your deployment. Nothing here is a secret."
ask SHUTTER_PROJECT_NAME "Railway project name:"
ask SHUTTER_GITHUB_REPOSITORY "Public GitHub repository (owner/repository):"
ask SHUTTER_RAILWAY_REGION "Railway region:"
ask SHUTTER_CONTROL_DOMAIN "Control custom domain (hostname only):"
ask SHUTTER_EDGE_WORKER_NAME "Cloudflare Worker name:"
ask SHUTTER_EDGE_DOMAIN "Edge custom domain (hostname only):"

stage "Cloudflare storage"
open_url "https://dash.cloudflare.com/"
step "Select Storage & databases, then R2, then Overview."
step "Copy the Account ID and S3 API endpoint shown on the R2 Overview page."
ask SHUTTER_R2_BUCKET "R2 Rendition Store bucket name:"
ask SHUTTER_R2_ENDPOINT "R2 S3 endpoint (https://ACCOUNT_ID.r2.cloudflarestorage.com):"
ask SHUTTER_R2_REGION "R2 S3 region (normally auto):"
ask SHUTTER_CLOUDFLARE_ZONE_ID "Cloudflare zone ID:"
ask SHUTTER_IMGPROXY_ALLOWED_SOURCES "Comma-separated HTTPS source allowlist:"
write_public_inputs
deployment_config render-edge >/dev/null
R2_PHASE="$(deployment_config cloudflare-phase)"
if [[ "$R2_PHASE" == "ready" ]]; then
  note "The R2 bucket and lifecycle were completed on an earlier run."
else
  if [[ "$R2_PHASE" == "changed" ]]; then
    warn "the R2 account or bucket changed since the last completed Cloudflare setup"
  fi
  if confirm "Ensure the R2 bucket exists and apply its cache/ lifecycle rule now?"; then
    if r2_bucket_exists; then
      note "The account-bound R2 bucket already exists; keeping it."
    else
      pnpm --filter @shutter/edge exec wrangler r2 bucket create \
        "$SHUTTER_R2_BUCKET" --config wrangler.deploy.jsonc
    fi
    pnpm --filter @shutter/edge exec wrangler r2 bucket lifecycle set \
      "$SHUTTER_R2_BUCKET" --config wrangler.deploy.jsonc \
      --file ../../infra/cloudflare/r2-lifecycle.json
    SHUTTER_R2_READY_ACCOUNT_ID="${SHUTTER_R2_ENDPOINT#https://}"
    SHUTTER_R2_READY_ACCOUNT_ID="${SHUTTER_R2_READY_ACCOUNT_ID%%.*}"
    write_env SHUTTER_R2_READY_ACCOUNT_ID "$SHUTTER_R2_READY_ACCOUNT_ID"
    write_env SHUTTER_R2_READY_BUCKET "$SHUTTER_R2_BUCKET"
  else
    warn "create the R2 bucket and lifecycle rule before the Worker deploy"
    SKIPPED+=("R2 bucket and cache/ lifecycle rule")
  fi
fi

stage "Railway topology plan"
BOOTSTRAP_PHASE="$(deployment_config bootstrap-phase)"
if [[ "$BOOTSTRAP_PHASE" == "unlinked" ]]; then
  say "No Railway project is linked yet."
  if confirm "Create and link a new empty Railway project now?"; then
    pnpm exec railway init --name "$SHUTTER_PROJECT_NAME"
  else
    warn "for an existing project, link it first: pnpm exec railway link"
    say "Then rerun this wizard."
    exit 1
  fi
  deployment_config bind-target
  BOOTSTRAP_PHASE="$(deployment_config bootstrap-phase)"
else
  deployment_config assert-target
fi
SHUTTER_RAILWAY_PROJECT_ID="$(_existing SHUTTER_RAILWAY_PROJECT_ID)"
SHUTTER_RAILWAY_ENVIRONMENT_ID="$(_existing SHUTTER_RAILWAY_ENVIRONMENT_ID)"
if [[ "$BOOTSTRAP_PHASE" == "linked" ]]; then
  deployment_config discover-volume
  BOOTSTRAP_PHASE="$(deployment_config bootstrap-phase)"
fi
if [[ "$BOOTSTRAP_PHASE" == "provisioned" ]]; then
  note "The live Jobs volume is recorded; the plan below declares it."
fi
say "This command only previews changes. Review every resource and variable."
pnpm deployment:plan
pause "Press Enter after you have reviewed the plan above."

stage "Explicit Railway apply"
if [[ "$BOOTSTRAP_PHASE" == "provisioned" ]]; then
  note "The topology apply was completed on an earlier run or project."
  SHUTTER_JOBS_VOLUME_NAME="$(_existing SHUTTER_JOBS_VOLUME_NAME)"
else
  say "The first plan intentionally has no credentials yet."
  step "In another terminal, review again and run: pnpm deployment:apply"
  warn "Do not continue until that explicit apply has created the services and database."
  pause "Return here only after the reviewed apply finishes."
  deployment_config discover-volume
  BOOTSTRAP_PHASE="$(deployment_config bootstrap-phase)"
  if [[ "$BOOTSTRAP_PHASE" != "provisioned" ]]; then
    warn "Railway does not report the new Jobs volume; rerun the wizard after the apply finishes"
    exit 1
  fi
  SHUTTER_JOBS_VOLUME_NAME="$(_existing SHUTTER_JOBS_VOLUME_NAME)"
fi

stage "Provider credentials"
deployment_config assert-target
load_control_vars
if existing_control_value EDGE_CONFIG_TOKEN >/dev/null; then
  say "Existing credentials were found on Shutter-Control. They are reused as"
  say "they are; this stage never regenerates a live credential."
else
  say "Credentials go directly to provider stores. This wizard never writes"
  say "them to disk or prints them."
fi
open_url "https://dash.cloudflare.com/"
step "Select Storage & databases, then R2, then Overview."
step "Under Account Details, select Manage next to API Tokens."
step "Create an Account or User API token with Object Read & Write for only this bucket."
step "Copy both one-time values from the confirmation page."
reuse_or_ask_secret S3_ACCESS_KEY_ID "R2 S3 access key ID:"
reuse_or_ask_secret S3_SECRET_ACCESS_KEY "R2 S3 secret access key:"
step "Open My Profile > API Tokens, select Create Token, then create a custom token."
step "Give it only Cache Purge permission for the selected zone and copy the one-time secret."
reuse_or_ask_secret CLOUDFLARE_CACHE_PURGE_TOKEN "Cloudflare Cache Purge API token:"

reuse_or_generate ADMIN_BOOTSTRAP_TOKEN
reuse_or_generate EDGE_CONFIG_TOKEN
reuse_or_generate IMGPROXY_KEY
reuse_or_generate IMGPROXY_SALT
reuse_or_generate IMGPROXY_SECRET
reuse_or_generate ORIGIN_AUTH_TOKEN
reuse_or_generate PDF_EXECUTOR_TOKEN
reuse_or_generate SHUTTER_ENCRYPTION_KEY
reuse_or_generate VIDEO_EXECUTOR_TOKEN

for target in Shutter-Control Shutter-Imgproxy Shutter-Executor-Video Shutter-Executor-PDF; do
  set_railway_value "$target" S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
  set_railway_value "$target" S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
done
set_railway_value Shutter-Control ADMIN_BOOTSTRAP_TOKEN "$ADMIN_BOOTSTRAP_TOKEN"
set_railway_value Shutter-Control CLOUDFLARE_CACHE_PURGE_TOKEN "$CLOUDFLARE_CACHE_PURGE_TOKEN"
set_railway_value Shutter-Control EDGE_CONFIG_TOKEN "$EDGE_CONFIG_TOKEN"
set_railway_value Shutter-Control IMGPROXY_KEY "$IMGPROXY_KEY"
set_railway_value Shutter-Control IMGPROXY_SALT "$IMGPROXY_SALT"
set_railway_value Shutter-Control IMGPROXY_SECRET "$IMGPROXY_SECRET"
set_railway_value Shutter-Control ORIGIN_AUTH_TOKEN "$ORIGIN_AUTH_TOKEN"
set_railway_value Shutter-Control PDF_EXECUTOR_TOKEN "$PDF_EXECUTOR_TOKEN"
set_railway_value Shutter-Control SHUTTER_ENCRYPTION_KEY "$SHUTTER_ENCRYPTION_KEY"
set_railway_value Shutter-Control VIDEO_EXECUTOR_TOKEN "$VIDEO_EXECUTOR_TOKEN"
set_railway_value Shutter-Imgproxy IMGPROXY_KEY "$IMGPROXY_KEY"
set_railway_value Shutter-Imgproxy IMGPROXY_SALT "$IMGPROXY_SALT"
set_railway_value Shutter-Imgproxy IMGPROXY_SECRET "$IMGPROXY_SECRET"
set_railway_value Shutter-Executor-PDF EXECUTOR_ROLE_TOKEN "$PDF_EXECUTOR_TOKEN"
set_railway_value Shutter-Executor-Video EXECUTOR_ROLE_TOKEN "$VIDEO_EXECUTOR_TOKEN"

set_worker_secret EDGE_CONFIG_TOKEN "$EDGE_CONFIG_TOKEN"
set_worker_secret ORIGIN_AUTH_TOKEN "$ORIGIN_AUTH_TOKEN"
set_worker_secret ORIGIN_BASE_URL "https://$SHUTTER_CONTROL_DOMAIN"
rm -f "$CONTROL_VARS_FILE"
CONTROL_VARS_FILE=""

# Record that credentials now exist on the providers. From here, plans
# preserve() the credential set and never propose deleting it.
write_env SHUTTER_SECRETS_SEEDED true
note "Read ADMIN_BOOTSTRAP_TOKEN later from the Railway dashboard:"
note "  Shutter-Control → Variables → ADMIN_BOOTSTRAP_TOKEN (needed for /admin)."

if confirm "Redeploy all Railway application services with the credentials now?"; then
  for target in Shutter-Control Shutter-Imgproxy Shutter-Executor-Video Shutter-Executor-PDF; do
    pnpm exec railway redeploy --yes --service "$target" \
      --project "$SHUTTER_RAILWAY_PROJECT_ID" \
      --environment "$SHUTTER_RAILWAY_ENVIRONMENT_ID" >/dev/null
    printf '  %s✓ redeployed%s %s\n' "$GREEN" "$RESET" "$target"
  done
else
  warn "all four Railway application services must be redeployed before verification"
  SKIPPED+=("redeploy Shutter-Control, Shutter-Imgproxy, and both Executors")
fi

stage "Final review and verification"
deployment_config render-edge >/dev/null
pnpm deployment:plan
say "This wizard does not apply the final plan or deploy the Worker."
step "Apply the final Railway plan only after review: pnpm deployment:apply"
step "Deploy Edge only after Control is healthy: pnpm deploy:edge"
step "Follow docs/runbooks/self-hosting.md to verify health and public/private Spaces."
SKIPPED+=("final Railway apply: pnpm deployment:apply")
SKIPPED+=("Edge Worker deploy: pnpm deploy:edge")
SKIPPED+=("live verification: docs/runbooks/self-hosting.md")
pause "Press Enter after you have reviewed the final plan above."

finish
if (( PROVIDER_SECRET_COUNT > 0 )); then
  note "set $PROVIDER_SECRET_COUNT provider secret value(s)"
fi
